export const FETCH_PUBLIC_USERS_START = "FETCH_PUBLIC_USERS_START";
export const FETCH_PUBLIC_USERS_SUCCESS = "FETCH_PUBLIC_USERS_SUCCESS";
export const FETCH_PUBLIC_USERS_FAIL = "FETCH_PUBLIC_USERS_FAIL";

export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const WHO_AMI_START = "WHO_AMI_START";
export const WHO_AMI_SUCCESS = "WHO_AMI_SUCCESS";
export const WHO_AMI_FAIL = "WHO_AMI_FAIL";
